name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Repo'yu çek
      uses: actions/checkout@v4

    - name: Rust kur
      uses: dtolnay/rust-toolchain@stable

    - name: Build (release)
      run: cargo build --release

    - name: EXE yükle
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: target/release/*.exe
